/**
 * certificatePresets.js
 * Comprehensive template definitions, design themes, calligraphy signatures,
 * and placeholder variable mappings for the Eventzone Certificate System.
 *
 * Horizontal A4 Dimensions: 297mm x 210mm (Aspect Ratio: 1.414 : 1)
 */

export const CERTIFICATE_CATEGORIES = [
  { id: "saved", label: "Saved" },
  { id: "all", label: "All Templates" },
  { id: "attendance", label: "Attendance & Participation" },
  { id: "speaker", label: "Speakers & Keynotes" },
  { id: "sponsor", label: "Sponsors & Partners" },
  { id: "exhibitor", label: "Exhibitors & Booths" },
  { id: "award", label: "Awards & Honors" },
  { id: "masterclass", label: "Workshops & Training" },
  { id: "custom", label: "Custom Artwork" },
];

export const FONT_PAIRINGS = [
  {
    id: "cinzel-sans",
    name: "Classic Roman (Cinzel & Plus Jakarta)",
    titleFont: "'Cinzel', serif",
    bodyFont: "'Plus Jakarta Sans', sans-serif",
    accentFont: "'Cinzel', serif",
    googleFonts: "Cinzel:wght@500;700;800;900&family=Plus+Jakarta+Sans:wght@400;500;600;700;800",
  },
  {
    id: "playfair-inter",
    name: "Luxury Editorial (Playfair & Inter)",
    titleFont: "'Playfair Display', serif",
    bodyFont: "'Plus Jakarta Sans', sans-serif",
    accentFont: "'Playfair Display', serif",
    googleFonts: "Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,600&family=Plus+Jakarta+Sans:wght@400;500;600;700",
  },
  {
    id: "montserrat-sans",
    name: "Modern Tech (Montserrat & Plus Jakarta)",
    titleFont: "'Montserrat', sans-serif",
    bodyFont: "'Plus Jakarta Sans', sans-serif",
    accentFont: "'Montserrat', sans-serif",
    googleFonts: "Montserrat:wght@600;700;800;900&family=Plus+Jakarta+Sans:wght@400;500;600;700",
  },
  {
    id: "cormorant-serif",
    name: "Academic Heritage (Cormorant & Serif)",
    titleFont: "'Cormorant Garamond', serif",
    bodyFont: "'Plus Jakarta Sans', sans-serif",
    accentFont: "'Cormorant Garamond', serif",
    googleFonts: "Cormorant+Garamond:ital,wght@0,600;0,700;1,600;1,700&family=Plus+Jakarta+Sans:wght@400;500;600;700",
  },
];

export const CALLIGRAPHY_SIGNATURES = [
  {
    id: "calligraphy-1",
    name: "Executive Swash (Great Vibes)",
    fontFamily: "'Great Vibes', cursive",
    fallbackText: "S. Jenkins",
  },
  {
    id: "calligraphy-2",
    name: "Classic Flourish (Alex Brush)",
    fontFamily: "'Alex Brush', cursive",
    fallbackText: "Alexandre M.",
  },
  {
    id: "calligraphy-3",
    name: "Royal Aristocratic (Pinyon Script)",
    fontFamily: "'Pinyon Script', cursive",
    fallbackText: "E. Rostova",
  },
  {
    id: "calligraphy-4",
    name: "Fluid Ribbon (Allura)",
    fontFamily: "'Allura', cursive",
    fallbackText: "T. Al-Mansoor",
  },
  {
    id: "calligraphy-5",
    name: "Parisian Vintage (Parisienne)",
    fontFamily: "'Parisienne', cursive",
    fallbackText: "Marcus V.",
  },
  {
    id: "calligraphy-6",
    name: "Modern Casual (Dancing Script)",
    fontFamily: "'Dancing Script', cursive",
    fallbackText: "Elena R.",
  },
  {
    id: "calligraphy-7",
    name: "Monoline Flow (Sacramento)",
    fontFamily: "'Sacramento', cursive",
    fallbackText: "Tariq M.",
  },
  {
    id: "calligraphy-8",
    name: "Expressive Brush (Satisfy)",
    fontFamily: "'Satisfy', cursive",
    fallbackText: "M. Vance",
  },
  {
    id: "calligraphy-9",
    name: "Ornate Engraver (Monsieur La Doulaise)",
    fontFamily: "'Monsieur La Doulaise', cursive",
    fallbackText: "Sarah J.",
  },
  {
    id: "calligraphy-10",
    name: "Natural Quill (Marck Script)",
    fontFamily: "'Marck Script', cursive",
    fallbackText: "A. Martin",
  },
];

export const BORDER_STYLES = [
  { id: "modern-geometric-navy-gold", name: "Modern Geometric Navy & Gold (Polygon Facets)" },
  { id: "fluid-wave-teal-gold", name: "Fluid Luxe Waves & Gold Ribbon" },
  { id: "corporate-diagonal-red-gold", name: "Executive Crimson & Charcoal Diagonal" },
  { id: "dark-obsidian-luxe", name: "Midnight Obsidian & Gold Crest (Dark Mode)" },
  { id: "asymmetric-royal-blue", name: "Asymmetric Royal Blue Modern Pillar" },
  { id: "emerald-botanical-crest", name: "Botanical Emerald & Gold Laurel" },
  { id: "creative-coral-violet", name: "Creative Tech Vanguard Wave (Gradient)" },
  { id: "classic-gold", name: "Classic Regal Double Gold Frame & Rosettes" },
  { id: "art-deco", name: "1920s Art Deco Stepped Angles & Diamonds" },
  { id: "corporate-navy", name: "Corporate Executive Navy Header & Footer Bands" },
  { id: "vintage-filigree", name: "Vintage Baroque Heritage Engraved Frame" },
  { id: "nordic-clean", name: "Swiss Minimalist Precision Grid & Crosshairs" },
  { id: "none", name: "None (Clean Full-Bleed Canvas)" },
];

export const DEFAULT_CERTIFICATE_TEMPLATES = [
  {
    id: "modern-geometric-navy-gold",
    name: "Modern Geometric Navy & Gold",
    category: "attendance",
    targetRole: "Attendee",
    styleId: "modern-geometric-navy-gold",
    accentColor: "#D4AF37",
    secondaryColor: "#0F172A",
    textColor: "#0F172A",
    bgStyle: "white",
    fontPairing: "montserrat-sans",
    borderStyle: "modern-geometric-navy-gold",
    certificateTitle: "CERTIFICATE OF ATTENDANCE",
    subtitleText: "THIS IS PROUDLY PRESENTED TO",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "For active and distinguished participation in the **{{event_name}}**, contributing to forward-looking industry innovation and executive discourse on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-GEO-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Dr. Sarah Jenkins",
        title: "Conference General Chair",
        org: "Eventzone Steering Board",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Alexandre Martin",
        title: "Executive Event Director",
        org: "Global Summit Committee",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-2",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "fluid-wave-teal-gold",
    name: "Fluid Luxe Waves & Gold Ribbon",
    category: "attendance",
    targetRole: "Attendee",
    styleId: "fluid-wave-teal-gold",
    accentColor: "#D4AF37",
    secondaryColor: "#0F766E",
    textColor: "#0F172A",
    bgStyle: "ivory",
    fontPairing: "playfair-inter",
    borderStyle: "fluid-wave-teal-gold",
    certificateTitle: "CERTIFICATE OF APPRECIATION",
    subtitleText: "THIS CERTIFICATE IS PROUDLY AWARDED TO",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{job_title}} • {{organization}}",
    bodyText: "In high recognition of valuable contributions and dedicated engagement throughout the **{{event_name}}** proceedings on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-WAV-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Elena Rostova",
        title: "Head of Operations",
        org: "Eventzone Committee",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-3",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Tariq Al-Mansoor",
        title: "Program Director",
        org: "Innovation Council",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-4",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "corporate-diagonal-red-gold",
    name: "Executive Crimson & Charcoal Diagonal",
    category: "attendance",
    targetRole: "Attendee",
    styleId: "corporate-diagonal-red-gold",
    accentColor: "#D4AF37",
    secondaryColor: "#991B1B",
    textColor: "#0F172A",
    bgStyle: "white",
    fontPairing: "montserrat-sans",
    borderStyle: "corporate-diagonal-red-gold",
    certificateTitle: "CERTIFICATE OF PARTICIPATION",
    subtitleText: "OFFICIALLY CONFERRED UPON",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "Having successfully completed all leadership seminars and executive masterclasses during the **{{event_name}}** held on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-CORP-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Marcus Vance",
        title: "Chief Executive Officer",
        org: "Corporate Leadership Group",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-5",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Sarah Jenkins",
        title: "Executive Director",
        org: "Eventzone Board",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "dark-obsidian-luxe",
    name: "Midnight Obsidian & Gold Crest",
    category: "award",
    targetRole: "Attendee",
    styleId: "dark-obsidian-luxe",
    accentColor: "#F59E0B",
    secondaryColor: "#F8FAFC",
    textColor: "#F8FAFC",
    bgStyle: "dark",
    fontPairing: "cinzel-sans",
    borderStyle: "dark-obsidian-luxe",
    certificateTitle: "AWARD OF EXCELLENCE",
    subtitleText: "IN HIGH RECOGNITION OF OUTSTANDING DISTINCTION",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "For extraordinary achievements, vision, and transformative leadership demonstrated during the prestigious **{{event_name}}** on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-LUXE-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Dr. Sarah Jenkins",
        title: "President of Jury",
        org: "Global Awards Council",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Tariq Al-Mansoor",
        title: "Grand Chancellor",
        org: "Strategic Excellence Board",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-4",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "asymmetric-royal-blue",
    name: "Asymmetric Royal Blue Pillar",
    category: "masterclass",
    targetRole: "Attendee",
    styleId: "asymmetric-royal-blue",
    accentColor: "#D4AF37",
    secondaryColor: "#1D4ED8",
    textColor: "#0F172A",
    bgStyle: "white",
    fontPairing: "montserrat-sans",
    borderStyle: "asymmetric-royal-blue",
    certificateTitle: "CERTIFICATE OF COMPLETION",
    subtitleText: "THIS RECOGNIZES THAT",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{job_title}} • {{organization}}",
    bodyText: "Has demonstrated technical proficiency and successfully completed the professional advanced training curriculum at **{{event_name}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-TRN-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Marcus Vance",
        title: "Lead Technical Instructor",
        org: "Advanced Engineering Council",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-5",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Elena Rostova",
        title: "Dean of Professional Studies",
        org: "Eventzone Academy",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-3",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "emerald-botanical-crest",
    name: "Botanical Emerald & Gold Laurel",
    category: "award",
    targetRole: "Attendee",
    styleId: "emerald-botanical-crest",
    accentColor: "#D4AF37",
    secondaryColor: "#064E3B",
    textColor: "#0F172A",
    bgStyle: "ivory",
    fontPairing: "cormorant-serif",
    borderStyle: "emerald-botanical-crest",
    certificateTitle: "HONORARY DIPLOMA",
    subtitleText: "CONFERRED BY THE SCIENTIFIC & SUSTAINABILITY COUNCIL",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "In celebration of exemplary dedication to green innovation, scientific integrity, and sustainable leadership presented at **{{event_name}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-EMR-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Prof. Sarah Jenkins, Ph.D.",
        title: "Chair of Scientific Council",
        org: "Global Research Forum",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Dr. Tariq Al-Mansoor",
        title: "Institute Director",
        org: "Sustainability Summit",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-4",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "creative-coral-violet",
    name: "Creative Tech Vanguard Wave",
    category: "masterclass",
    targetRole: "Attendee",
    styleId: "creative-coral-violet",
    accentColor: "#F43F5E",
    secondaryColor: "#7C3AED",
    textColor: "#0F172A",
    bgStyle: "white",
    fontPairing: "montserrat-sans",
    borderStyle: "creative-coral-violet",
    certificateTitle: "INNOVATION & DESIGN AWARD",
    subtitleText: "PROUDLY PRESENTED TO",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{job_title}} • {{organization}}",
    bodyText: "For visionary breakthrough design, creative coding excellence, and innovative project presentation at the **{{event_name}}** Hackathon.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-DES-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Elena Rostova",
        title: "Head of Product & Design",
        org: "Vanguard Hackathon",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-3",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Marcus Vance",
        title: "Chief Innovation Officer",
        org: "NextGen Creative Lab",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-5",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "classic-gold",
    name: "Classic Regal Gold Filigree",
    category: "attendance",
    targetRole: "Attendee",
    styleId: "classic-gold",
    accentColor: "#D4AF37",
    secondaryColor: "#1E293B",
    textColor: "#0F172A",
    bgStyle: "ivory",
    fontPairing: "cinzel-sans",
    borderStyle: "classic-gold",
    certificateTitle: "CERTIFICATE OF ATTENDANCE",
    subtitleText: "THIS IS PROUDLY PRESENTED TO",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "For distinguished participation in **{{event_name}}**, contributing to strategic collaboration held on **{{event_date}}** at **{{event_location}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-REG-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Dr. Sarah Jenkins",
        title: "General Chair",
        org: "Summit Board",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Alexandre Martin",
        title: "Executive Director",
        org: "Organizing Committee",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-2",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "art-deco",
    name: "1920s Gatsby Art Deco",
    category: "award",
    targetRole: "Attendee",
    styleId: "art-deco",
    accentColor: "#C59B27",
    secondaryColor: "#18181B",
    textColor: "#18181B",
    bgStyle: "ivory",
    fontPairing: "cinzel-sans",
    borderStyle: "art-deco",
    certificateTitle: "AWARD OF EXCELLENCE",
    subtitleText: "IN HIGH RECOGNITION OF EXCEPTIONAL MASTERY",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "Having demonstrated peerless standard of achievement and creative mastery during the **{{event_name}}** Grand Gala on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-DEC-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Dr. Sarah Jenkins",
        title: "President of Jury",
        org: "Summit Board",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Tariq Al-Mansoor",
        title: "Academic Chair",
        org: "Excellence Institute",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-4",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "speaker-appreciation",
    name: "Keynote Speaker Honor",
    category: "speaker",
    targetRole: "Speaker",
    styleId: "corporate-diagonal-red-gold",
    accentColor: "#D97706",
    secondaryColor: "#0F172A",
    textColor: "#0F172A",
    bgStyle: "ivory",
    fontPairing: "playfair-inter",
    borderStyle: "corporate-diagonal-red-gold",
    certificateTitle: "CERTIFICATE OF APPRECIATION",
    subtitleText: "HONORABLY PRESENTED TO DISTINGUISHED SPEAKER",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{job_title}} — {{organization}}",
    bodyText: "With deepest appreciation for delivering an inspiring keynote presentation and sharing transformative insights at **{{event_name}}** on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-SPK-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Dr. Sarah Jenkins",
        title: "President & Chair",
        org: "Global Summit Committee",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Tariq Al-Mansoor",
        title: "Program Curator",
        org: "Eventzone Summit",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-4",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "sponsor-partnership",
    name: "Corporate Partner & Sponsor",
    category: "sponsor",
    targetRole: "Sponsor",
    styleId: "corporate-navy",
    accentColor: "#1E40AF",
    secondaryColor: "#0F172A",
    textColor: "#0F172A",
    bgStyle: "white",
    fontPairing: "montserrat-sans",
    borderStyle: "corporate-navy",
    certificateTitle: "CERTIFICATE OF PARTNERSHIP",
    subtitleText: "PROUDLY AWARDED TO OUR VALUED PARTNER",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "In sincere gratitude for your invaluable sponsorship and dedicated partnership at **{{event_name}}**. Your support empowered world-class collaboration.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-SPN-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Alexandre Martin",
        title: "Head of Partnerships",
        org: "Eventzone Platform",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-2",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Dr. Sarah Jenkins",
        title: "Executive Director",
        org: "Summit Steering Committee",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
  {
    id: "custom-artwork-canvas",
    name: "Custom Graphic Artwork Canvas",
    category: "custom",
    targetRole: "Attendee",
    styleId: "custom-artwork",
    accentColor: "#D4AF37",
    secondaryColor: "#0F172A",
    textColor: "#0F172A",
    bgStyle: "white",
    fontPairing: "cinzel-sans",
    borderStyle: "none",
    certificateTitle: "OFFICIAL CERTIFICATION",
    subtitleText: "PRESENTED WITH DISTINCTION TO",
    recipientNamePlaceholder: "{{name}}",
    recipientSubtext: "{{organization}}",
    bodyText: "For distinguished achievement and professional merit conferred at **{{event_name}}** on **{{event_date}}**.",
    issuerName: "{{organizer_name}}",
    issueDateText: "Issued on {{issue_date}}",
    certificateIdPrefix: "EZ-CST-2026",
    signatories: [
      {
        id: "sig-1",
        name: "Dr. Sarah Jenkins",
        title: "General Chair",
        org: "Executive Committee",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-1",
        signatureImage: "",
      },
      {
        id: "sig-2",
        name: "Alexandre Martin",
        title: "Managing Director",
        org: "Eventzone Platform",
        signatureType: "calligraphy",
        calligraphyId: "calligraphy-2",
        signatureImage: "",
      },
    ],
    customBgUrl: "",
  },
];

export function interpolateCertificateText(templateString = "", contextData = {}) {
  if (!templateString || typeof templateString !== "string") return "";

  return templateString.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (match, key) => {
    const normalizedKey = key.toLowerCase();
    
    if (normalizedKey === "name" || normalizedKey === "fullname") {
      return contextData.name || contextData.fullName || "Jane Doe";
    }
    if (normalizedKey === "organization" || normalizedKey === "company" || normalizedKey === "companyname") {
      return contextData.company || contextData.organization || "";
    }
    if (normalizedKey === "role" || normalizedKey === "tickettype") {
      return contextData.role || contextData.ticketType || "Delegate";
    }
    if (normalizedKey === "job_title" || normalizedKey === "jobtitle" || normalizedKey === "title") {
      return contextData.jobTitle || contextData.title || "";
    }
    if (normalizedKey === "event_name" || normalizedKey === "eventtitle" || normalizedKey === "event") {
      return contextData.eventName || contextData.eventTitle || "Eventzone Global Summit 2026";
    }
    if (normalizedKey === "event_location" || normalizedKey === "location" || normalizedKey === "venue") {
      return contextData.eventLocation || contextData.location || "Algiers, Algeria";
    }
    if (normalizedKey === "event_date" || normalizedKey === "dates" || normalizedKey === "eventdates") {
      return contextData.eventDate || contextData.dates || "October 14–16, 2026";
    }
    if (normalizedKey === "issue_date" || normalizedKey === "issuedate") {
      return contextData.issueDate || new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
    }
    if (normalizedKey === "certificate_id" || normalizedKey === "cert_id" || normalizedKey === "certid") {
      return contextData.certificateId || contextData.certId || "EZ-CERT-0001";
    }
    if (normalizedKey === "organizer_name" || normalizedKey === "issuer_name") {
      return contextData.organizerName || contextData.issuerName || "Eventzone Organizing Committee";
    }
    if (normalizedKey === "custom_notes" || normalizedKey === "notes") {
      return contextData.customNotes || "";
    }

    return contextData[key] !== undefined ? contextData[key] : match;
  });
}

export function formatCertificateBodyHtml(bodyText = "", contextData = {}) {
  const interpolated = interpolateCertificateText(bodyText, contextData);
  return interpolated
    .replace(/\*\*(.*?)\*\*/g, '<strong class="font-extrabold text-slate-900">$1</strong>')
    .replace(/\*(.*?)\*/g, '<em class="italic">$1</em>')
    .replace(/\n/g, '<br />');
}
